### ISSUE TITLE
Inconsistent error tuples

### ISSUE THREAD

**Issue by nick-rossi** [mkleehammer/pyodbc#1206]
I'm using pyodbc to perform tasks to insert data in sql server database. I wanted to catch certain errors and it looks like the error tuples generated do not follow a consistent structure. This makes it harder to handle errors dynamically in code. 

For example:

```
pyodbc.IntegrityError: ('23000', "[23000] [Microsoft][ODBC SQL Server Driver][SQL Server]Violation of UNIQUE KEY constraint 'UC_EventId'. Cannot insert duplicate key in object 'table. (2627) (SQLExecDirectW); [23000] [Microsoft][ODBC SQL Server Driver][SQL Server]The statement has been terminated. (3621)")

pyodbc.ProgrammingError: ('The SQL contains 16 parameter markers, but 15 parameters were supplied', 'HY000')
```

So `IntegrityError` has structure: `(code, message)` and `ProgrammingError` has structure `(message, code)` . 

I wanted to do something in python like:

```
handle_errors = ["23000", "HY000"]
if ex.args[0] in recoverable_errors:
    do_something()
```

But this will not work as intended because of pyodbc's inconsistent error tuple structure. For the above example, the `ProgrammingError` code will be overlooked.

**Comment by mkleehammer** [comment]
That is a problem.  Also, I'd rather be able to get at the SQLSTATE directly via `ex.sqlstate`.

I wanted to end the 4.x line, but I would consider swapped constructor parameters a serious enough error to put out another release.  I'll try to complete it this weekend.

**Comment by RobertLD** [comment]
I think it's worth establishing a more standard model for errors across the board. My issue isn't 100% the same but I have a set of error codes returned from MSSQL for errors in business logic. I'd like some way to access the returned error-code rather than having to do some string-splitting magic

**Comment by bkline** [comment]
Here's my analysis for this ticket.

## Exception argument ordering

The April 2023 comment notwithstanding, the original bug is still present in `pyodbc` 5.3.0. It's possible that a fix made its way into 4.x but fell on the floor in the transition to 5.x, though I haven't been able to find such a fix yet. I believe I could come up with a PR to make the order consistent, as long as there's consensus as to which order is "correct" (the OP's description implies that the state code should come _before_ the message, which seems reasonable). It's at least theoretically possible that there's code out there in the wild which relies in some convoluted way on this bug, though that would make for a very edgy case, and given that the inconsistency itself is a bug and not a documented contract it doesn't seem like this would need a deprecation cycle. Certainly warrants a changelog warning, though.

## New attribute

That same comment alludes to the creation of a new `sqlstate` attribute on the `Exception` object being raised, and the `RaiseErrorV()` function has this note immediately above the code to create that object:

```c
    // Create an exception with a 'sqlstate' attribute (set to None if we don't have one) whose 'args' attribute is a
    // tuple containing the message and sqlstate value.  The 'sqlstate' attribute ensures it is easy to access in
    // Python (and more understandable to the reader than ex.args[1]), but putting it in the args ensures it shows up
    // in logs because of the default repr/str.
```

... which makes it looks as if that attribute has already been implemented. However, I can't find any evidence in the code that this has actually happened, and ...

```
>>> e1.sqlstate
Traceback (most recent call last):
  File "<python-input-24>", line 1, in <module>
    e1.sqlstate
AttributeError: 'ProgrammingError' object has no attribute 'sqlstate'
>>> e2.sqlstate
Traceback (most recent call last):
  File "<python-input-25>", line 1, in <module>
    e2.sqlstate
AttributeError: 'IntegrityError' object has no attribute 'sqlstate'
```

## Exposure of native error code

The enhancement request made in the August 2023 comment, asking that the native error code which is exposed by the ODBC APIs be added as a separate attribute is really orthogonal to this bug report, and should be in its own ticket.
