### ISSUE TITLE
pyodbc unable to run queries with large list of values in 'IN' clause on SQL Server

### ISSUE THREAD

**Issue by abhipalsingh** [mkleehammer/pyodbc#1218]
### Environment
- Python: 3.10.6
- pyodbc: 4.0.39
- SQLAlchemy: 2.0.12
- OS: Ubuntu 22.04
- DB: Microsoft SQL Server 2019
- driver: ODBC Driver 18 for SQL Server

### Issue
Observed behavior:
Sample query: `SELECT x, y, z FROM dbo.tbl_data WHERE x IN (1,2,3 ... 2500)`
SQL SELECT query issued has an IN clause with ~2500 `integer` values in it. Query fails when executed using SQLAlchemy and Pyodbc with below error:

```
pyodbc.Error: ('07002', '[07002] [Microsoft][ODBC Driver 18 for SQL Server]COUNT field incorrect or syntax error (0) (SQLExecDirectW)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/usr/app/.venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2688, in all
    return self._iter().all()  # type: ignore
  File "/home/usr/app/.venv/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2842, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
  File "/home/usr/app/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2231, in execute
    return self._execute_internal(
  File "/home/usr/app/.venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2126, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/home/usr/app/.venv/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 292, in orm_execute_statement
    result = conn.execute(
  File "/home/usr/app/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1413, in execute
    return meth(
  File "/home/usr/app/.venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 483, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/usr/app/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1637, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/usr/app/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1841, in _execute_context
    return self._exec_single_context(
  File "/home/usr/app/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1982, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/usr/app/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2339, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/usr/app/.venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1963, in _exec_single_context
    self.dialect.do_execute(
  File "/home/usr/app/.venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 920, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DBAPIError: (pyodbc.Error) ('07002', '[07002] [Microsoft][ODBC Driver 18 for SQL Server]COUNT field incorrect or syntax error (0) (SQLExecDirectW)')
```

The SELECT statement works fine when run directly on `SQL server`. 
It also works with `SQL Alchemy` and `pymssql`.

Expected behavior:
pyodbc SQL query should work consistently with `SQL server`.

**Comment by abhipalsingh** [comment]
I am not sure if I fully understand this. When you say, the query is executed as a stored proc, does pyodbc create a temporary proc? Is this implementation documented anywhere?

The same query works with pymssql but not with pyodbc. So, there is something that pyodbc does differently than SQL server or pymssql.

I do understand that having an IN clause with too many values is not optimal, but pyodbc behaviour should still be consistent with SQL server itself or pymssql.

**Comment by v-chojas** [comment]
If you are submitting the query with literal values in the IN, those do not count as parameters.
That may be what pymssql does, but I don't know.

**Comment by gordthompson** [comment]
@abhipalsingh 

> When you say, the query is executed as a stored proc, does pyodbc create a temporary proc?

No, in this case the SQL Server ODBC driver invokes the built-in system stored procedure `sp_prepexec`.


@v-chojas 

> If you are submitting the query with literal values in the IN, those do not count as parameters. That may be what pymssql does, but I don't know.

Yes, pymssql does parameter substitution on the client side, so it will send

```sql
SELECT * FROM table_name WHERE x IN (11, 22, 33)
```

whereas pyodbc will (effectively) send

```sql
SELECT * FROM table_name WHERE x IN (@P1, @P2, @P3)
```

with parameter values `@P1=11`, `@P2=22`, and `@P3=33`.

**Comment by v-chojas** [comment]
That explains it. The server doesn't see parameters so those don't count towards the 2100 limit.
