### ISSUE TITLE
Pyodbc v5 Informix SqlDriverConnect Error

### ISSUE THREAD

**Issue by PyodbcUnix** [mkleehammer/pyodbc#1392]
### Environment

- Python: 3.10
- pyodbc: 5.2.0
- OS: Ubuntu 22.04
- DB: Informix
- driver: InformixClient SDK 4.10

### Issue

Hello together,

First i want to thank you for providing this cool package!
I updated my System to pyodbc 5.2.0 and now i get back the error SQLDriverConnect.w -11060 SQLError.

With pyodbc 4.0.39 everything works fine.
Hope you can help me...

**Comment by gordthompson** [comment]
It would be helpful if you could create [ODBC trace logs](https://github.com/mkleehammer/pyodbc/wiki/Troubleshooting-%E2%80%93-Generating-an-ODBC-trace-log) when calling `pyodbc.connect()` for both cases — 4.0.39 (successful) and 5.2.0 (unsuccessful) — and post the logs here as file attachments.

**Comment by asser** [comment]
I've been having the same problem for a while, attaching the ODBC trace log here. It's a simple `pyodbc.connect(dsn='database')` call.

[odbctrace.log](https://github.com/user-attachments/files/18262088/odbctrace.log)

Does it contain anything useful?

I was trying to replicate the issue directly in C code, with `SQLDriverConnectW()`, hoping to find out what changed from 4.0.39 to 5.x, but gave up temporarily :)

**Comment by asser** [comment]
Here's the trace log for Pyodbc 4.0.39: 
[odbctrace-4.0.39.log](https://github.com/user-attachments/files/18262275/odbctrace-4.0.39.log)


It seems actually that `SQLDriverConnectW()` also fails, but it then falls back to `SQLDriverConnect()` which succeeds. That would explain why 5.x doesn't work, since `SQLDriverConnect()` was removed in commit 5c1f1c0 ?

No idea why `SQLDriverConnectW()` wouldn't work though.

**Comment by PyodbcUnix** [comment]
Hi @asser,

first thank you for Debugging that problem! Did you use the same Informix Client?

@gordthompson is it possible to do a Bugfix on that? Would be really great!

Wish you a nice year!

**Comment by PyodbcUnix** [comment]
Hi @asser 

can you try to add this in the odbc.ini or if there is already an ODBC section the following:

[ODBC]
UNICODE=UCS-2

Please also try to change UCS-2 to UCS-4 after test fail.

BG

**Comment by asser** [comment]
@PyodbcUnix Yes, it's already set to `UCS-2` (in odbcinst.ini) and I've tried variations for it directly in odbc.ini - UTF-8, UCS-4, UCS-2, no value - all with the same error.

I've opened a support request now with our Informix supplier, hopefully they can help. I'll report back.

At this point I believe it's more of a driver issue or maybe unixODBC, causing `SQLDriverConnectW()` to always fail.

**Comment by asser** [comment]
Heard back from our supplier, unfortunately their support don't want to help out since they don't provide the Informix DB to us directly. A bit disappointing, even if it makes sense (their product is a package/application backed by Informix).

I don't have other ways of raising the issue with IBM, but if anybody does it would be good :)

**Comment by PyodbcUnix** [comment]
Hi @asser,

Oh thats unfortunately not good. But in odbcinst.ini you also did the tests in odbc.ini without the option in odbcinst.ini?

Maybe we have to change the wording of the connection string. I dont know. Im going crazy...

BG 
Flo

**Comment by PyodbcUnix** [comment]
@gordthompson @mkleehammer i think there are more Environment or driver issues with the Connect W functions. Would it be possible that you add the ANSI again like it was in pyodbc 4.x.x?

Thanks for your help!

BG

**Comment by asser** [comment]
> Oh thats unfortunately not good. But in odbcinst.ini you also did the tests in odbc.ini without the option in odbcinst.ini?
> 
> Maybe we have to change the wording of the connection string. I dont know. Im going crazy...

Sorry I didn't follow up on this - I think I had the option in odbcinst.ini at the same time yes. I'll see if I can try it without.

I got inspired to try out some C code today, and found out how to directly link against the Informix libraries without going through unixODBC. And it seems that:

```
ret = SQLDriverConnectW(V_OD_hdbc, 0, (SQLWCHAR *) L"dsn=economi", SQL_NTS, 0, 0, 0, SQL_DRIVER_NOPROMPT);
```

works, while:

```
ret = SQLDriverConnectW(V_OD_hdbc, 0, (SQLWCHAR *) u"dsn=economi", SQL_NTS, 0, 0, 0, SQL_DRIVER_NOPROMPT);
```

does *not* work ("economi" is the DSN I configured in odbc.ini).

So the problem might then be in the encoding of the connection string passed to the driver? I have no idea how unixODBC handles this, or if it's possible to control without modifying unixODBC.

Any ideas? I'm happy to try out anything, I'm not sure where to go from here, except see if I can get connect to work linking against unixODBC and trying different string encoding (but need to read up on some more code first) ;-)

**Comment by PyodbcUnix** [comment]
Hi,

@asser i also tried multiple different settings and strings but unfortunately failed. 
And yes it has definetly something to do with the unicode and encoding.
Hope you'll get a solution on this. Otherwise the only thing would be using the non wide Charakter functions.

BG

**Comment by asser** [comment]
Thanks for following up on it so quickly! It's not a big issue for me, at the moment we're happily using pyodbc 4.0.39 anyway.

I'll probably dive some more into it later to satisfy my own curiousity :)

**Comment by PyodbcUnix** [comment]
Yeah its not a big issue now but in 2027 there is no support for python 3.11 anymore...

**Comment by asser** [comment]
Ok, this was a bit interesting. I messed around with unixODBC and built a local copy with `CFLAGS=-DSQL_WCHART_CONVERT` set.

This makes `SQLDriverConnectW()` with L-string work:

```
ret = SQLDriverConnectW(V_OD_hdbc, 0, (SQLWCHAR *) L"dsn=economi", SQL_NTS, 0, 0, 0, SQL_DRIVER_NOPROMPT);
```

As in it connects successfully to Informix.

`SQL_WCHART_CONVERT` forces `SQLWCHAR` to be defined as type of `wchar_t` instead of `unsigned short`.

So there seems to be some mismatch between the type definition of `SQLWCHAR` between unixODBC and the Informix CSDK, which I guess leads to the problem.

pyodbc didn't like my newly built library at all, and returned an error padded with \x00:

```
Traceback (most recent call last):
  File "/home/asser/projects/unilaan-python-backend/test-odbc/../test-odbc.py", line 6, in <module>
    db = pyodbc.connect(dsn='economi')
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyodbc.Error: ('IM0', '[IM0] [\x00u\x00n\x00i\x00x\x00O\x00D\x00B\x00C\x00]\x00[\x00D\x00r\x00i\x00v\x00e\x00r\x00 \x00M\x00a\x00n\x00a\x00g\x00e\x00r\x00]\x00D\x00a\x00t\x00a\x00 \x00s\x00o\x00u\x00r\x00c\x00e\x00 \x00n\x00a\x00m\x00e\x00 (0) (SQLDriverConnect)')
```

To be fair, I didn't yet recompile pyodbc against my modified unixODBC, which will be the next step when I return to this.

**Comment by asser** [comment]
I suppose at this point I should raise the issue with unixODBC ;)

**Comment by PyodbcUnix** [comment]
Hi @asser,

do you have some news here?

**Comment by mkr-ac** [comment]
Hi there!

Struggling with the same issue. Any updates?

@asser few questions:
1. You've diagnosed the issue to be caused by a mismatch between unixODBC and Informix CSDK. However, I'm not really sure, which one of these is in fact causing the issue (by just reading, you could have just adapted unixODBC to broken Informix CSDK, that could have worked, but other drivers might not work with your new version, do they?).
2. I've looked into the unixODBC's GH and could not find any related issue. Have you reported it?
Thanks!

**Comment by asser** [comment]
Hi, sorry for the lack of response. I haven't had the opportunity to investigate this further, so I have no updates to share either unfortunately. For now the project I am working on is happy with Pyodbc v4.

Re. your questions @mkr-ac ,

1. No I'm not sure at all here either. That's why I was thinking to raise the issue with unixODBC, as they might be able to provide some more guidance.
2. I did not report the issue. If you do that, do feel free to tag me in case I can contribute with something :)

**Comment by mkr-ac** [comment]
Hi @asser,

I spent some time researching and Copiloting the issue.

1. Microsoft Standard says, that `SQLWCHAR` is `wchar_t`. However, `wchar_t` on Windows refers to `UTF-16`, and therefore is 2 bytes long.
2. Most ODBC drivers, which are ported to Linux from Windows, implement this on linux side as `unsigned short`. In fact, it appears that everyone except Informix does it like this (at least Copilot-based research returned this result, take it with a grain of salt :) ).
3. I believe that's the reason why unixODBC uses `unsigned short` as default - it's compatible with about everyone except Informix.
4. IBM says on [Informix documentation pages](https://www.ibm.com/docs/en/informix-servers/15.0.0?topic=unicode-supported-functions): `The ODBC specification defines these functions with the wchar_t data type.` and they implement it like so, but using Linux-standard `wchar_t` literally. That is 4-bytes `int`. The only ones in the world, and they're proud of it.

So, I can't even imagine feasible solution. Answer from colleagues was - just use JDBC...

Unfortunately, downgrading to pyodbc v4 would cause chain reaction of downgrading and end up in complete rebuild of containers, which I want to avoid. So, I quite probably will have to let it be and follow my colleague's advice...

**Comment by PyodbcUnix** [comment]
Hi together,

wouldn't it be good if this project would have again that also the possibility without the W function? As it Was in pyodbc before? What should be the disadvantage?

BG

**Comment by PyodbcUnix** [comment]
@gordthompson @mkleehammer @keitherskine could you please implement that back?

**Comment by kadler** [comment]
Never mind, I think you **also** need to build your unixODBC with `-DSQL_WCHART_CONVERT` in order for that to work. The above will encode the string in to the correct encoding that the Informix driver wants, but then unixODBC will have no clue how to read it and will not be able to know which driver it should load (can't read the DSN or DRIVER keywords). If you leave the encoding as UTF-16, then unixODBC knows how to interpret it, but when it passes it to the driver, the driver doesn't understand.

**Comment by mkr-ac** [comment]
@kadler  I'd love to try... But not sure why, I can't even make it through to the ODBC driver...

```
Traceback (most recent call last):
  File "/tmp/informix_test.py", line 2, in <module>
    db=pyodbc.connect('DSN=<redacted>;LoginID=<redacted>;pwd=<redacted>', encoding='utf-32-le')
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyodbc.InterfaceError: ('IM002', '[IM002] [unixODBC][Driver Manager]Data source name not found and no default driver specified (0) (SQLDriverConnect)')
```
but with utf-16 it works... 
```
Traceback (most recent call last):
  File "/tmp/informix_test.py", line 2, in <module>
    db=pyodbc.connect('DSN=<redacted>;LoginID=<redacted>;pwd=<redacted>', encoding='utf-16-le')
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pyodbc.Error: ('H00o\x03', '[H00o\x03] 䥛普牯業嵸䥛普牯業⁸䑏䍂䐠楲敶嵲敇敮慲\u206c牥潲\u2e72 (-11060) (SQLDriverConnect)')
```

So it seems that connect string expects utf-32-le connect string (maybe not?). But simple conversion of connect string to utf-32-le did not help... Either I did it wrong (not a python guru), or it's not that straightforward...

code
``` python
import pyodbc

cs='DSN=<redacted>;LoginID=<redacted>;pwd=<redacted>'
cs32=cs.encode('utf-32-le')
db=pyodbc.connect(cs32, encoding='utf-32-le')
```
returns
```
Traceback (most recent call last):
  File "/tmp/informix_test.py", line 5, in <module>
    db=pyodbc.connect(cs32, encoding='utf-32-le')
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument 1 must be a string or unicode object
```

Any ideas are welcome...

**Comment by bkline** [comment]
@mkleehammer As noted in #1433 I'm investigating what would be involved in restoring the ability to connect without the wide-character ODBC functions. My first step is to review the discussion that went into the removal of that path in order to understand what the rationale behind that change was. I found your [commit](https://github.com/mkleehammer/pyodbc/commit/5c1f1c0), but its comment just says "Eliminate deprecated Unicode API" and I can't find the PR. Can you point me to some discussion explaining what led to this change? Thanks! 🙏

**Comment by bkline** [comment]
I found that if I add this line 

```ini
UNICODE=UCS-2
```

to the `[ODBC]` section of `~/.odbc.ini`, then the connection succeeds.

### Repro script

```python
import pyodbc
cursor = pyodbc.connect("DSN=ibmifx").cursor()
sql = "SELECT DBINFO('version', 'full') FROM systables WHERE tabid = 1"
print(cursor.execute(sql).fetchone()[0])
```

### $HOME/.odbc.ini

```ini
[ibmifx]
Description   = Connection using the IBM ODBC driver
Driver        = Informix
Database      = odbc_demodb
UID           = informix
PWD           = REDACTED
ServerName    = informix
Host          = localhost
Service       = 9088
Protocol      = onsoctcp

[ODBC]
UNICODE=UCS-2  ; remove this line and the connection will fail
```

### /etc/odbcinst.ini
```ini
[Informix]
Description      = IBM Informix ODBC Driver
Driver           = /home/bkline/packages/IBM/Informix.15.0.1.0/lib/cli/iclit15a.so
Setup            = /home/bkline/packages/IBM/Informix.15.0.1.0/lib/cli/iclit15a.so
APILevel         = 1
ConnectFunctions = YYY
DriverODBVer     = 03.51
SQLLevel         =  1
```

### Test

```bash
$ python repro.py
IBM Informix Dynamic Server Version 14.10.FC9W1DE
```

### Environment

| Component | Version |
|----|----|
| Python | 3.12.3
| pyodbc | 5.1.0 and 5.3.0 |
| OS | Ubuntu 22.04 |
| DB | IBM Informix Dynamic Server Version 14.10.FC9W1DE |
| Driver | IBM Informix 15.0.1.0 Client SDK (also tested with OneDB's driver version 09b) |

@PyodbcUnix If this works for your environment, can you confirm here (and close the ticket if you think that's appropriate)?

@mkleehammer In my reading of the ODBC documentation I get the impression that the assumption that all drivers will support the wide-character APIs is unwarranted, so although no longer needed for this ticket (assuming the O.P. agrees), I'd still be interested in any discussion about eliminating the "ANSI" connection path you could point me to.

**Comment by PyodbcUnix** [comment]
@bkline unfortunately it still doesn't work.
The only difference is that i have to use for DB_LOCALE=en_US.CP1252

We use the iclis09b driver.  

Do you mean UCS-2 or UTF-2?

BG

**Comment by bkline** [comment]
@PyodbcUnix UCS-2 (UTF-2 isn't a thing, and if it were you wouldn't be able to encode much with it 😅).

Can you share (with all sensitive information redacted)?
* the output from `odbcinst -j`
* the output from `env | grep -i ODBC`
* the relevant portions of `/etc/odbcinst.ini`
* the relevant portions of `/etc/odbc.ini`
* the relevant portions of `$HOME/.odbc.ini`
* your Python repro script

**Comment by pjwelsh** [comment]
I'm also not having any luck with 14.10 latest Informix, CSDK 4.50 and pyodbc 5.1. That includes adding the UNICODE=UCS-2 option.
I continue to get the "pyodbc.Error: ('H000', '[H000] [ (-11060) (SQLDriverConnect)')"
Anyone find additional information or answers?

**Comment by pjwelsh** [comment]
Sigh... I spoke too soon it seems. It appears the example section of code I started with was:
[ODBC]
UNICODE       = UCS-2

However, based on another comment I saw asking to remove spaces for the pairs, this now working:
[ODBC]
UNICODE=UCS-2

I beleive removing of spaces is all I changed from the simple example created above.

**Comment by bkline** [comment]
@pjwelsh You're right. It shouldn't make any difference, but it does. I have fixed my example in the comment above.

Perhaps IBM sees its ecosystem as a universe unto itself, which therefore doesn't have to pay any attention to the standard INI syntax: https://www.ibm.com/docs/en/informix-servers/14.10.0?topic=application-configuration

**Comment by pjwelsh** [comment]
Also, a working pyodbc 5.1 + Informix is *only* possible when the ~/.odbc.ini is populated with the DSN and "[ODBC]" entries. The same information in the system file /etc/odbc.ini and the "[ODBC]" entry in either /etc/odbc.ini or /etc/odbcinst.ini do *NOT* work and will continue to error. However, the core Driver information can still be in the /etc/odbcinst.ini.
Something magic is happening with the ~/.odbc.ini that is different than the /etc/odbc.ini.
Env: AlmaLinux 10.2 fully updated, python 3.12, CSDK 4.50FC12.

**Comment by PyodbcUnix** [comment]
@bkline @pjwelsh 

That's the thing. Creating a separate .odb.ini in the home folder and adding this line

UNICODE=UCS-2

to the [ODBC] section, then the connection succeeds.

It's important that you choose exactly the path from odbcinst -j. At my last try i forgot to add a point at the file name in front (.odbc.ini)

I don't understand why, but it works. Thank you all for your help. Amazing :)

**Comment by asser** [comment]
> It's important that you choose exactly the path from odbcinst -j. At my last try i forgot to add a point at the file name in front (.odbc.ini)

Thank you, this saved me a headache.

On a new system I'm setting up, `odbcinst -j` has `USER DATA SOURCES..: /etc/odbc.ini` and thus I had to add the `UNICODE=UCS-2` line to /etc/odbc.ini rather than ~/.odbc.ini for it to work.

It's a little ridiculous, but thank you everyone for figuring it out so we can use PyODBC 5+ 😁
