### ISSUE TITLE
Error when the type of a column is CLOB

### ISSUE THREAD

**Issue by dlopes7** [mkleehammer/pyodbc#146]
`Traceback (most recent call last):
  File "./query_oracle.py", line 54, in execute_query
    for row in cursor:
  File "/usr/local/lib/python3.5/site-packages/pypyodbc-1.3.3-py3.5.egg/pypyodbc.py", line 1917, in __next__
    return self.next()
  File "/usr/local/lib/python3.5/site-packages/pypyodbc-1.3.3-py3.5.egg/pypyodbc.py", line 1920, in next
    row = self.fetchone()
  File "/usr/local/lib/python3.5/site-packages/pypyodbc-1.3.3-py3.5.egg/pypyodbc.py", line 1898, in fetchone
    raw_value = ''.join(raw_data_parts)
TypeError: sequence item 0: expected str instance, bytes found
`
I believe there are some special characters on this table since the column holds XML values.

**Comment by mkleehammer** [comment]
That is from a different product.  This is "pyodbc" and that is "pypyodbc".  Good luck, though.
