### ISSUE TITLE
Install from pypi fails due to hardcoded path in pyodbc.egg-info/SOURCES.txt

### ISSUE THREAD

**Issue by tgc-dk** [mkleehammer/pyodbc#157]
The title more or less says it all..
I tried to build pyodbc on windows from pypi but ended up with the traceback below. I believe it is caused by some hardcoded paths in pyodbc.egg-info/SOURCES.txt, such as /Users/mkleehammer/dev/pyodbc/src/buffer.cpp

The build traceback:

```
    Creating library build\temp.win32-3.4\Release\src\pyodbc.lib and object build\temp.win32-3.4\Release\src\pyodbc.exp
    running install_lib
    copying build\lib.win32-3.4\pyodbc.pyd -> C:\Python34\Lib\site-packages
    running install_egg_info
    running egg_info
    writing pyodbc.egg-info\PKG-INFO
    writing top-level names to pyodbc.egg-info\top_level.txt
    writing dependency_links to pyodbc.egg-info\dependency_links.txt
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'pyodbc.egg-info\SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\appveyor\AppData\Local\Temp\1\pip-build-s4yolscg\pyodbc\setup.py", line 319, in <module>
        main()
      File "C:\Users\appveyor\AppData\Local\Temp\1\pip-build-s4yolscg\pyodbc\setup.py", line 112, in main
        setup(**kwargs)
      File "C:\Python34\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Python34\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Python34\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Python34\lib\distutils\command\install.py", line 551, in run
        self.run_command(cmd_name)
      File "C:\Python34\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Python34\lib\site-packages\setuptools\command\install_egg_info.py", line 33, in run
        self.run_command('egg_info')
      File "C:\Python34\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Python34\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Python34\lib\site-packages\setuptools\command\egg_info.py", line 180, in run
        self.find_sources()
      File "C:\Python34\lib\site-packages\setuptools\command\egg_info.py", line 207, in find_sources
        mm.run()
      File "C:\Python34\lib\site-packages\setuptools\command\egg_info.py", line 291, in run
        self.add_defaults()
      File "C:\Python34\lib\site-packages\setuptools\command\egg_info.py", line 327, in add_defaults
        self.read_manifest()
      File "C:\Python34\lib\site-packages\setuptools\command\sdist.py", line 196, in read_manifest
        self.filelist.append(line)
      File "C:\Python34\lib\site-packages\setuptools\command\egg_info.py", line 232, in append
        path = convert_path(item)
      File "C:\Python34\lib\distutils\util.py", line 125, in convert_path
        raise ValueError("path '%s' cannot be absolute" % pathname)
    ValueError: path '/Users/mkleehammer/dev/pyodbc/src/buffer.cpp' cannot be absolute
```

**Comment by mkleehammer** [comment]
Thanks.  This was something that was just fixed in the latest version, but I don't think I uploaded a Python 3.4 binary for Windows.  I would guess that you are, therefore, picking up the previous version without the fix.  Can you tell me what version of pyodbc is getting installed?  3.0.x has the problem, 3.1 has the fix.

In the meantime, I'll upload a 3.4 / 32-bit wheel.  It may take a while.  I don't think I have 3.4 on my build box anymore.

**Comment by tgc-dk** [comment]
I downgraded to 3.0.10 which works. I assumed that pip downloaded 3.1.1 and started building from source...

**Comment by mkleehammer** [comment]
I just now uploaded some Python 3.4 binary wheels for Windows.  Sorry about the wait - I hadn't started my Windows VM in months and it literally took hours for the Windows updates to stop using 100% CPU.

**Comment by tgc-dk** [comment]
It works now - thank you for your work!
