### ISSUE TITLE
TypeError: not enough arguments for format string

### ISSUE THREAD

**Issue by dapicester** [mkleehammer/pyodbc#211]
Hi, I am using django 1.10 with pyodbc/freetds to connect with Sqlserver.

I am able to reproduce the error in the object any time I use django ORM `annotate()` and `order_by` and slicing the queryset.
It seems that there are more param placeholders than the actual number of params.

Better to explain with code (I tried to extract a minimal example from our codebase):

```python
from django.db import models
from django.db.models import Q, Count, Case, When, IntegerField

class User(models.Model):
    id = models.BigAutoField(primary_key=True)
    email = models.CharField()

query = User.objects.annotate(
    gmail=Count(
      Case(When(Q(email__icontains='gmail.com'), then=1), output_field=IntegerField())) \
).filter(gmail__gte=1).order_by('gmail')

# this is OK
query.all()

# this fails:
query.all()[1:]
```

Here is the error:
```
/Users/paolo/.pyenv/versions/sc3-2.7/lib/python2.7/site-packages/sql_server/pyodbc/base.pyc in format_sql(self, sql, params)
    500         # pyodbc uses '?' instead of '%s' as parameter placeholder.
    501         if params is not None:
--> 502             sql = sql % tuple('?' * len(params))
    503
    504         return sql

TypeError: not enough arguments for format string
```
And with `pdb` I found that:
```
(Pdb) sql
u"SELECT * FROM (SELECT [User].[ID] AS Col1, [TB_User].[Email] AS Col2, COUNT_BIG(CASE WHEN UPPER([TB_User].[Email]) LIKE UPPER(%s) ESCAPE '\\' THEN %s ELSE NULL END) AS [gmail], ROW_NUMBER() OVER (ORDER BY COUNT(CASE WHEN UPPER([TB_User].[Email]) LIKE UPPER(%s) ESCAPE '\\' THEN %s ELSE NULL END) ASC) AS [rn] FROM [TB_User] GROUP BY [TB_User].[ID], [TB_User].[Email] HAVING COUNT_BIG(CASE WHEN UPPER([TB_User].[Email]) LIKE UPPER(%s) ESCAPE '\\' THEN %s ELSE NULL END) >= %s) AS X WHERE X.rn BETWEEN 2 AND 22 ORDER BY X.rn"
(Pdb) params
(u'%gmail.com%', 1, u'%gmail.com%', 1, 1)
(Pdb) len(params)
5
(Pdb) sql.count('%s')
7
```

Here is the full error trace:
```
Traceback (most recent call last):
  File "/Users/paolo/Projects/sidechef3/api/tests/utils.py", line 32, in wrapper
    return f(*args, **kwargs)
  File "/Users/paolo/Projects/sidechef3/api/management/commands/find_bug.py", line 40, in handle
    print(query.all()[1:])
  File "/Users/paolo/.pyenv/versions/sc3-2.7/lib/python2.7/site-packages/django/db/models/query.py", line 232, in __repr__
    data = list(self[:REPR_OUTPUT_SIZE + 1])
  File "/Users/paolo/.pyenv/versions/sc3-2.7/lib/python2.7/site-packages/django/db/models/query.py", line 256, in __iter__
    self._fetch_all()
  File "/Users/paolo/.pyenv/versions/sc3-2.7/lib/python2.7/site-packages/django/db/models/query.py", line 1087, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Users/paolo/.pyenv/versions/sc3-2.7/lib/python2.7/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql()
  File "/Users/paolo/.pyenv/versions/sc3-2.7/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 835, in execute_sql
    cursor.execute(sql, params)
  File "/Users/paolo/.pyenv/versions/sc3-2.7/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/paolo/.pyenv/versions/sc3-2.7/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/paolo/.pyenv/versions/sc3-2.7/lib/python2.7/site-packages/sql_server/pyodbc/base.py", line 534, in execute
    sql = self.format_sql(sql, params)
  File "/Users/paolo/.pyenv/versions/sc3-2.7/lib/python2.7/site-packages/sql_server/pyodbc/base.py", line 502, in format_sql
    sql = sql % tuple('?' * len(params))
TypeError: not enough arguments for format string
```

**Comment by keitherskine** [comment]
At first glance, this looks like an issue in [django](https://github.com/django/django) or [django-pyodbc](https://github.com/lionheart/django-pyodbc) (my guess would be django), but not pyodbc.  There is clearly something going wrong with the number of parameters, but that's happening before pyodbc gets involved.

I believe the reference to "pyodbc" at the end of that stack trace is misleading.  pyodbc doesn't have a `base.py` file, but django-pyodbc does.

**Comment by dapicester** [comment]
Thanks for the quick response. Actually we use [django-pyodbc-azure](https://github.com/michiya/django-pyodbc-azure), I will report the issue to them as well.
