### ISSUE TITLE
32bit odbc connection to sybase ase

### ISSUE THREAD

**Issue by giuliohome** [mkleehammer/pyodbc#293]
### Environment

- Python: 32-bit Python 2.7
- pyodbc: pypyodbc-1.3.5 from https://pypi.python.org/pypi/pypyodbc
- OS: Win7 (64-bit)
- DB: Sybase ASE 
- driver: ODBC driver for Adaptive Server Enterprise

### Issue

"expected behavior"
I'd like to connect to the DB without errors.
 "observed behavior"
I execute the following lines

```
import sys
sys.path.insert(0, 'C:\mypath\pypyodbc-1.3.5')
import pypyodbc
conn = pypyodbc.connect(r'uid=xxxx;pwd=xxxx;DRIVER={Adaptive Server Enterprise};port=1234;server=11.222.333.444;charset=iso_1;')
```

and the last one gives an error (it seems that the charset is the issue)

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\mypath\pypyodbc-1.3.5\pypyodbc.py", line 2454, in __init__
    self.connect(connectString, autocommit, ansi, timeout, unicode_results, readonly)
  File "C:\mypath\pypyodbc-1.3.5\pypyodbc.py", line 2528, in connect
    check_success(self, ret)
  File "C:\mypath\pypyodbc-1.3.5\pypyodbc.py", line 1009, in check_success
    ctrl_err(SQL_HANDLE_DBC, ODBC_obj.dbc_h, ret, ODBC_obj.ansi)
  File "C:\mypath\pypyodbc-1.3.5\pypyodbc.py", line 985, in ctrl_err
    raise Error(state,err_text)
pypyodbc.Error: (u'HY092', u'[HY092] [Sybase][ODBC Driver]Invalid attribute or option identifier')
```

**Comment by giuliohome** [comment]
Excuseme: now I've done 

```
c:\Python27\Scripts\pip.exe install pyodbc
Collecting pyodbc
  Downloading pyodbc-4.0.19-cp27-cp27m-win32.whl (50kB)
    100% |################################| 51kB 1.1MB/s
Installing collected packages: pyodbc
Successfully installed pyodbc-4.0.19
```

And it did the trick
