### ISSUE TITLE
Unable to connect to databases

### ISSUE THREAD

**Issue by chillheart** [mkleehammer/pyodbc#338]
### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.6.3
- pyodbc: 4.0.21
- OS: CentOS Linux release 7.4.1708
- DB: MSSQL 2014, Teradata
- driver: ODBC Driver 13 for SQL Server, tdodbc 16.10
- unixODBC: 2.3.1

### Issue

**Observed Behavior**

When trying to make a connection to SQL Server from Python 3.6 using pyodbc, I am receiving the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Unable to set SQL_ATTR_CONNECTION_POOLING attribute.
```

This error is also occuring when I type `pyodbc.drivers()` at the command line.

I have done some research and unixODBC does not support connection pooling as of 2.3.4, however I am currently using 2.3.1. None the less, I have tried to turn off pooling using `pyodbc.pooling = False` at which point I receive a different error.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 3: invalid start byte
```
odbc.ini
```
[ITSM]
Driver = ODBC Driver 13 for SQL Server
Server = servername,port
Trusted_Connection = yes
ANSI = True

[Terdata]
Driver = Teradata Database ODBC Driver 16.20
DBCName = servername
```
odbcinst.ini
```
[ODBC Driver 13 for SQL Server]
Description=Microsoft ODBC Driver 13 for SQL Server
Driver=/opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.1.so.9.1
UsageCount=1

[Teradata Database ODBC Driver 16.20]
Description=Teradata Database ODBC Driver 16.20
Driver=/opt/teradata/client/ODBC_64/lib/tdataodbc_sb64.so
UsageCount=1
```
Python code
```python
import pyodbc

pyodbc.pooling = False

conn = pyodbc.connect("DSN=ITSM")

```

I have also turned on tracing in unixODBC and I am able to successfully connect using isql. I do not see any trace logs when attempting to connect using pyodbc.

**Comment by v-chojas** [comment]
Connection pooling is only partly implemented in unixODBC 2.3.1, but nonetheless it should still silently accept attempts to set the attribute. Thus, I believe you may be using an even older version of unixODBC or have multiple versions installed --- what does the output of `odbcinst -j` show?

Also, the output of the following commands will be useful for further diagnosis:

```
ldd `which odbcinst`
ldd `which isql`
ldd /opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.1.so.9.1
```

**Comment by chillheart** [comment]
odbcinst -j
```
unixODBC 2.3.1
DRIVERS............: /etc/odbcinst.ini
SYSTEM DATA SOURCES: /etc/odbc.ini
FILE DATA SOURCES..: /etc/ODBCDataSources
USER DATA SOURCES..: /home/chillheart/.odbc.ini
SQLULEN Size.......: 8
SQLLEN Size........: 8
SQLSETPOSIROW Size.: 8
```
ldd \`which odbcinst\`
```
linux-vdso.so.1 =>  (0x00007ffce79b9000)
libodbcinst.so.2 => /lib64/libodbcinst.so.2 (0x00007ff8ebebd000)
libltdl.so.7 => /lib64/libltdl.so.7 (0x00007ff8ebcb3000)
libdl.so.2 => /lib64/libdl.so.2 (0x00007ff8ebaae000)
libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ff8eb892000)
libc.so.6 => /lib64/libc.so.6 (0x00007ff8eb4cf000)
/lib64/ld-linux-x86-64.so.2 (0x000055d92b2e9000)
```
ldd \`which isql\`
```
linux-vdso.so.1 =>  (0x00007ffd4c7f7000)
libodbc.so.2 => /lib64/libodbc.so.2 (0x00007f6008432000)
libltdl.so.7 => /lib64/libltdl.so.7 (0x00007f6008228000)
libreadline.so.6 => /lib64/libreadline.so.6 (0x00007f6007fe1000)
libdl.so.2 => /lib64/libdl.so.2 (0x00007f6007ddd000)
libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f6007bc1000)
libc.so.6 => /lib64/libc.so.6 (0x00007f60077fd000)
libtinfo.so.5 => /lib64/libtinfo.so.5 (0x00007f60075d3000)
/lib64/ld-linux-x86-64.so.2 (0x0000557f8b536000)
```
ldd /opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.1.so.9.1
```
linux-vdso.so.1 =>  (0x00007ffc759bb000)
libdl.so.2 => /lib64/libdl.so.2 (0x00007fe355f52000)
librt.so.1 => /lib64/librt.so.1 (0x00007fe355d4a000)
libodbcinst.so.2 => /lib64/libodbcinst.so.2 (0x00007fe355b37000)
libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007fe3556d6000)
libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007fe3553ee000)
libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007fe3551a0000)
libcurl.so.4 => /lib64/libcurl.so.4 (0x00007fe354f37000)
libssl.so.10 => /lib64/libssl.so.10 (0x00007fe354cc5000)
libuuid.so.1 => /lib64/libuuid.so.1 (0x00007fe354abf000)
libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fe3547b7000)
libm.so.6 => /lib64/libm.so.6 (0x00007fe3544b5000)
libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fe35429e000)
libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fe354082000)
libc.so.6 => /lib64/libc.so.6 (0x00007fe353cbf000)
/lib64/ld-linux-x86-64.so.2 (0x0000556d042d9000)
libltdl.so.7 => /lib64/libltdl.so.7 (0x00007fe353ab4000)
libz.so.1 => /lib64/libz.so.1 (0x00007fe35389e000)
libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007fe35366b000)
libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007fe353466000)
libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007fe353258000)
libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007fe353054000)
libresolv.so.2 => /lib64/libresolv.so.2 (0x00007fe352e39000)
libidn.so.11 => /lib64/libidn.so.11 (0x00007fe352c06000)
libssh2.so.1 => /lib64/libssh2.so.1 (0x00007fe3529dc000)
libssl3.so => /lib64/libssl3.so (0x00007fe35278f000)
libsmime3.so => /lib64/libsmime3.so (0x00007fe352568000)
libnss3.so => /lib64/libnss3.so (0x00007fe35223e000)
libnssutil3.so => /lib64/libnssutil3.so (0x00007fe352010000)
libplds4.so => /lib64/libplds4.so (0x00007fe351e0c000)
libplc4.so => /lib64/libplc4.so (0x00007fe351c07000)
libnspr4.so => /lib64/libnspr4.so (0x00007fe3519c8000)
liblber-2.4.so.2 => /lib64/liblber-2.4.so.2 (0x00007fe3517b9000)
libldap-2.4.so.2 => /lib64/libldap-2.4.so.2 (0x00007fe351565000)
libselinux.so.1 => /lib64/libselinux.so.1 (0x00007fe35133d000)
libsasl2.so.3 => /lib64/libsasl2.so.3 (0x00007fe35111f000)
libpcre.so.1 => /lib64/libpcre.so.1 (0x00007fe350ebd000)
libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007fe350c86000)
libfreebl3.so => /lib64/libfreebl3.so (0x00007fe350a82000)
```

**Comment by v-chojas** [comment]
Thank you. That output shows that all the utilities and the ODBC driver are linked to the same DM, which is 2.3.1. One more thing to check:

```
ldd `python -c "exec('import pyodbc\nprint(pyodbc.__file__)')"`
```
(Substitute `python` with however you invoke your Python, e.g. `python3` or `python3.6` or etc.)

**Comment by chillheart** [comment]
ldd \`python3 -c "exec('import pyodbc\nprint(pyodbc.__file__)')"\`
```
linux-vdso.so.1 =>  (0x00007ffc4e344000)
libodbc.so => /lib64/libodbc.so (0x00007f5c20c98000)
libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f5c20990000)
libm.so.6 => /lib64/libm.so.6 (0x00007f5c2068d000)
libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f5c20477000)
libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f5c2025b000)
libc.so.6 => /lib64/libc.so.6 (0x00007f5c1fe97000)
librt.so.1 => /lib64/librt.so.1 (0x00007f5c1fc8f000)
libodbcinst.so => /lib64/libodbcinst.so (0x00007f5c1fa5f000)
libddicu27.so => /lib64/libddicu27.so (0x00007f5c1eb63000)
libdl.so.2 => /lib64/libdl.so.2 (0x00007f5c1e95f000)
/lib64/ld-linux-x86-64.so.2 (0x00005579aebf5000)
```

**Comment by v-chojas** [comment]
Observe that all the previous libraries are linking to libodbc.so.*2* and libodbcinst.so.*2* but your pyODBC is linking to libodbc.so and libodbcinst.so (without the .2) . That's probably a very old version --- see what `ls -l /lib64/libodbc*` outputs on your machine... you have at least 2 different versions of unixODBC installed and pyODBC is linking to the wrong one.

The solution is to remove the old unixODBC (unless you have other applications which need it and would be broken by the newer versions) and pyODBC, then install unixODBC >= 2.3.1 and pyODBC.

**Comment by chillheart** [comment]
Thank you very much! It appears that the Teradata ODBC drivers have their own libodbc.so
```
/lib64/libodbc.so -> /opt/teradata/client/16.20/lib64/libodbc.so
```
