### ISSUE TITLE
Django, invalid precision value when inserting more than 4000 characters into TextField

### ISSUE THREAD

**Issue by titomisa** [mkleehammer/pyodbc#359]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.5.2
- pyodbc: 4.0.22 (issue does not happen with 4.0.21)
- OS: windows 7 64-bit
- DB: sql server 2014
- driver: ODBC Driver 13 for SQL Server
-django 1.11.9

I have a model that contains a filed "question_text" of type TextField.
When I try to insert something of small length (1000 char) it works fine.
However, when I try to insert something bigger (4001 char or more) it throws an Invalid precision value error.

Models
```
class Question(models.Model):
    question_text = models.TextField()
    pub_date = models.DateTimeField()
```
Tests
```
class Tests(TransactionTestCase):
    def test_text_field_fail(self):
        a = 'a'*8000
        q = Question(question_text=a, pub_date=datetime.datetime.now())
        q.save()

    def test_text_field_pass(self):
        a = 'a' * 100
        q = Question(question_text=a, pub_date=datetime.datetime.now())
        q.save()
```
Settings
```
DATABASES = {
    'default': {
        'ENGINE': 'sql_server.pyodbc',
		'HOST': '----',
        'NAME': '----',
		'USER': '----',
		'PASSWORD': '---',
		'OPTIONS': {'driver': 'ODBC Driver 13 for SQL Server',},
    }
}
```

**Comment by v-makouz** [comment]
Can you post the ODBC trace? And what's the DB schema?

**Comment by titomisa** [comment]
Django error
```
  File "C:\Users\alberto.misail\AppData\Local\Programs\Python\Python35\lib\site-
packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\alberto.misail\AppData\Local\Programs\Python\Python35\lib\site-
packages\sql_server\pyodbc\base.py", line 520, in execute
    return self.cursor.execute(sql, params)
pyodbc.Error: ('HY104', '[HY104] [Microsoft][ODBC Driver 13 for SQL Server]Inval
id precision value (0) (SQLBindParameter)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "R:\Personal Folders\Alberto Misail\Database 2.0\Django  code\BatteryPars
er2Django2\parserdb2\tests.py", line 10, in test_text_field_fail
    q.save()
  File "C:\Users\alberto.misail\AppData\Local\Programs\Python\Python35\lib\site-
packages\django\db\models\base.py", line 729, in save
    force_update=force_update, update_fields=update_fields)
  File "C:\Users\alberto.misail\AppData\Local\Programs\Python\Python35\lib\site-
packages\django\db\models\base.py", line 759, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, upda
te_fields)
  File "C:\Users\alberto.misail\AppData\Local\Programs\Python\Python35\lib\site-
packages\django\db\models\base.py", line 842, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Users\alberto.misail\AppData\Local\Programs\Python\Python35\lib\site-
packages\django\db\models\base.py", line 880, in _do_insert
    using=using, raw=raw)
  File "C:\Users\alberto.misail\AppData\Local\Programs\Python\Python35\lib\site-
packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\alberto.misail\AppData\Local\Programs\Python\Python35\lib\site-
packages\django\db\models\query.py", line 1125, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Users\alberto.misail\AppData\Local\Programs\Python\Python35\lib\site-
packages\django\db\models\sql\compiler.py", line 1283, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\alberto.misail\AppData\Local\Programs\Python\Python35\lib\site-
packages\django\db\backends\utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._e
xecute)
  File "C:\Users\alberto.misail\AppData\Local\Programs\Python\Python35\lib\site-
packages\django\db\backends\utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\alberto.misail\AppData\Local\Programs\Python\Python35\lib\site-
packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\alberto.misail\AppData\Local\Programs\Python\Python35\lib\site-
packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\alberto.misail\AppData\Local\Programs\Python\Python35\lib\site-
packages\django\db\backends\utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\alberto.misail\AppData\Local\Programs\Python\Python35\lib\site-
packages\sql_server\pyodbc\base.py", line 520, in execute
    return self.cursor.execute(sql, params)
django.db.utils.Error: ('HY104', '[HY104] [Microsoft][ODBC Driver 13 for SQL Ser
ver]Invalid precision value (0) (SQLBindParameter)')
```
Find attached the ODBC trace
[SQL.LOG](https://github.com/mkleehammer/pyodbc/files/1794261/SQL.LOG)

Schema:
the table is called dbo.parserdb2_question
So the schema would be dbo

**Comment by v-makouz** [comment]
Thanks for the ODBC trace
I should have said "table schema", not DB, I meant column types, as in if I wanted to create the same table to try to repro.

**Comment by titomisa** [comment]
There are three columns:
-id (primary key): Integer filed in django translated to int in MS SQL
-question: Text field in django translated to nvarchar(MAX) in MS SQL
-pub_date: Date time field in django translated to datetime2(7) in MS SQL

You can also find this information in the model code in the initial post

**Comment by v-makouz** [comment]
Alright, thanks, I'm looking into it

**Comment by stefanhdao** [comment]
I've experienced something similar with the following settings:

Python: 3.7.6
pyodbc: 4.0.22 (issue does not happen with 4.0.21)
OS: Ubuntu
DB: sql server 2012
driver: FreeTDS
-django 1.10.4

**Comment by v-makouz** [comment]
I've attempted to reproduce this on Windows 7 (64 bit) with Microsoft ODBC Driver 13 for SQL Server 13.0.4413.46 and pyODBC 4.0.22 running against SQL Server 2014 and was able to insert 80,000 characters with no issues (I've tried on multiple other configs as well). 

Looking at the ODBC traces, it seems that the problems starts when SQLDescribeParam fails, with "Invalid Descriptor Index", even though the parameter requested is number 1 and SQLNumParams returned 2. After that fails the SQLBindParameter has incorrect parameters and fails. I'm not at all familiar with django, is it possible that it does something to affect SQLDescribeParam?

**Comment by mkleehammer** [comment]
Can you retest with 4.0.23?  I've backed out the problematic changes in 4.0.22.

**Comment by ldiego2601** [comment]
I can confirm that with pyodbc v4.0.23 the issue is **not** present.

Got the same issue posted before when putting (DB write operation) large JSONs in the session object when using MSSQL as the session engine for Django. This with pyodbc v4.0.22.

- Python: v3.5.2

- pyodbc: v4.0.22 (issue does not happen with 4.0.23)

- OS: Ubuntu server 16.04

- DB: MSSQL 2008R2 v10.50.6000.34

- driver: ODBC Driver 13 for SQL Server v13.1.9.2-1

- Django v2.0.3

Traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/dist-packages/sql_server/pyodbc/base.py", line 546, in execute
    return self.cursor.execute(sql, params)
pyodbc.Error: ('HY104', '[HY104] [Microsoft][ODBC Driver 13 for SQL Server]Invalid precision value (0) (SQLBindParameter)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.5/dist-packages/django/utils/deprecation.py", line 97, in __call__
    response = self.process_response(request, response)
  File "/usr/local/lib/python3.5/dist-packages/django/contrib/sessions/middleware.py", line 58, in process_response
    request.session.save()
  File "/usr/local/lib/python3.5/dist-packages/django/contrib/sessions/backends/db.py", line 85, in save
    obj.save(force_insert=must_create, force_update=not must_create, using=using)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 729, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 759, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 823, in _save_table
    forced_update)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/base.py", line 872, in _do_update
    return filtered._update(values) > 0
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/query.py", line 709, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/sql/compiler.py", line 1377, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/usr/local/lib/python3.5/dist-packages/django/db/models/sql/compiler.py", line 1066, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/dist-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.5/dist-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/dist-packages/sql_server/pyodbc/base.py", line 546, in execute
    return self.cursor.execute(sql, params)
django.db.utils.Error: ('HY104', '[HY104] [Microsoft][ODBC Driver 13 for SQL Server]Invalid precision value (0) (SQLBindParameter)')
```

**Comment by titomisa** [comment]
@mkleehammer retested, everything is working beautifully. Thanks

**Comment by leezimu516** [comment]
I have a similar issue with pyodbc v4.0.28 which is latest. I tested pyodbc v4.0.23 which works perfectly.
Can you retest pyodbc v4.0.28?

**Comment by v-chojas** [comment]
Can you provide an ODBC trace? Also open a new issue since this one is already closed.

**Comment by leezimu516** [comment]
> Can you provide an ODBC trace? Also open a new issue since this one is already closed.

open new ticket #710
