### ISSUE TITLE
Automatic tests for sqlite has several failures

### ISSUE THREAD

**Issue by dhamonex** [mkleehammer/pyodbc#437]
Hi,

I've tried to execute the the automatic test cases for sqlite and as result I get 14 failures and 1 error. I've attached the output below.

I'm not sure if this  are this serious errors or if the test cases have to be corrected.

Thanks in advance.

My environment was as followed:

```
Python version: Python 3.6.5
pyodbc version: 4.0.23
sqliteodbc version: sqliteodbc 0.9995
OS: openSUSE Tumbleweed
sqlite version: sqlite3 3.24.0
```

```
python3 tests3/sqlitetests.py -v "Driver=SQLITE3;Database=sqlite.db"
python:  3.6.5 (default, Mar 31 2018, 19:45:04) [GCC]
pyodbc:  4.0.23 /home/dhartman/Entwicklung/rpmbuild/home:Monex:Database/python-pyodbc/pyodbc-4.0.23/build/lib.linux-x86_64-3.6/pyodbc.cpython-36m-x86_64-linux-gnu.so
odbc:    03.52
driver:  sqlite3odbc.so 0.9995
         supports ODBC version 03.00
os:      Linux
unicode: Py_Unicode=4 SQLWCHAR=2
Max VARCHAR = 255
Max WVARCHAR = (not supported)
Max BINARY = (not supported)
..FFFFFFFFFFFF.F..............E....................F.....................
======================================================================
ERROR: test_large_update_nodata (__main__.SqliteTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests3/sqlitetests.py", line 660, in test_large_update_nodata
    hundredkb = bytearray('x'*100*1024)
TypeError: string argument without an encoding

======================================================================
FAIL: test_blob_0 (__main__.SqliteTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests3/sqlitetests.py", line 221, in t
    self._test_strtype('blob', bytearray(value), len(value))
  File "tests3/sqlitetests.py", line 148, in _test_strtype
    self.assertEqual(type(v), type(value))
AssertionError: <class 'bytes'> != <class 'bytearray'>

======================================================================
FAIL: test_blob_1 (__main__.SqliteTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests3/sqlitetests.py", line 221, in t
    self._test_strtype('blob', bytearray(value), len(value))
  File "tests3/sqlitetests.py", line 148, in _test_strtype
    self.assertEqual(type(v), type(value))
AssertionError: <class 'bytes'> != <class 'bytearray'>

======================================================================
FAIL: test_blob_1023 (__main__.SqliteTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests3/sqlitetests.py", line 221, in t
    self._test_strtype('blob', bytearray(value), len(value))
  File "tests3/sqlitetests.py", line 148, in _test_strtype
    self.assertEqual(type(v), type(value))
AssertionError: <class 'bytes'> != <class 'bytearray'>

======================================================================
FAIL: test_blob_1024 (__main__.SqliteTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests3/sqlitetests.py", line 221, in t
    self._test_strtype('blob', bytearray(value), len(value))
  File "tests3/sqlitetests.py", line 148, in _test_strtype
    self.assertEqual(type(v), type(value))
AssertionError: <class 'bytes'> != <class 'bytearray'>

======================================================================
FAIL: test_blob_2047 (__main__.SqliteTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests3/sqlitetests.py", line 221, in t
    self._test_strtype('blob', bytearray(value), len(value))
  File "tests3/sqlitetests.py", line 148, in _test_strtype
    self.assertEqual(type(v), type(value))
AssertionError: <class 'bytes'> != <class 'bytearray'>

======================================================================
FAIL: test_blob_2048 (__main__.SqliteTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests3/sqlitetests.py", line 221, in t
    self._test_strtype('blob', bytearray(value), len(value))
  File "tests3/sqlitetests.py", line 148, in _test_strtype
    self.assertEqual(type(v), type(value))
AssertionError: <class 'bytes'> != <class 'bytearray'>

======================================================================
FAIL: test_blob_255 (__main__.SqliteTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests3/sqlitetests.py", line 221, in t
    self._test_strtype('blob', bytearray(value), len(value))
  File "tests3/sqlitetests.py", line 148, in _test_strtype
    self.assertEqual(type(v), type(value))
AssertionError: <class 'bytes'> != <class 'bytearray'>

======================================================================
FAIL: test_blob_256 (__main__.SqliteTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests3/sqlitetests.py", line 221, in t
    self._test_strtype('blob', bytearray(value), len(value))
  File "tests3/sqlitetests.py", line 148, in _test_strtype
    self.assertEqual(type(v), type(value))
AssertionError: <class 'bytes'> != <class 'bytearray'>

======================================================================
FAIL: test_blob_4000 (__main__.SqliteTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests3/sqlitetests.py", line 221, in t
    self._test_strtype('blob', bytearray(value), len(value))
  File "tests3/sqlitetests.py", line 148, in _test_strtype
    self.assertEqual(type(v), type(value))
AssertionError: <class 'bytes'> != <class 'bytearray'>

======================================================================
FAIL: test_blob_510 (__main__.SqliteTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests3/sqlitetests.py", line 221, in t
    self._test_strtype('blob', bytearray(value), len(value))
  File "tests3/sqlitetests.py", line 148, in _test_strtype
    self.assertEqual(type(v), type(value))
AssertionError: <class 'bytes'> != <class 'bytearray'>

======================================================================
FAIL: test_blob_511 (__main__.SqliteTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests3/sqlitetests.py", line 221, in t
    self._test_strtype('blob', bytearray(value), len(value))
  File "tests3/sqlitetests.py", line 148, in _test_strtype
    self.assertEqual(type(v), type(value))
AssertionError: <class 'bytes'> != <class 'bytearray'>

======================================================================
FAIL: test_blob_512 (__main__.SqliteTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests3/sqlitetests.py", line 221, in t
    self._test_strtype('blob', bytearray(value), len(value))
  File "tests3/sqlitetests.py", line 148, in _test_strtype
    self.assertEqual(type(v), type(value))
AssertionError: <class 'bytes'> != <class 'bytearray'>

======================================================================
FAIL: test_context_manager (__main__.SqliteTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests3/sqlitetests.py", line 651, in test_context_manager
    self.assertRaises(pyodbc.ProgrammingError, test)
AssertionError: ProgrammingError not raised by test

======================================================================
FAIL: test_rowcount_select (__main__.SqliteTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests3/sqlitetests.py", line 351, in test_rowcount_select
    self.assertEquals(self.cursor.rowcount, count)
AssertionError: 0 != 4

----------------------------------------------------------------------
Ran 73 tests in 0.108s

FAILED (failures=14, errors=1)
```

**Comment by mkleehammer** [comment]
Reproduced.  Have to look at these one by one.

[sqliteodbc docs](http://www.ch-werner.de/sqliteodbc/html/index.html)

**Comment by dhamonex** [comment]
Thanks for checking. I've seen that the exit code is always 0 regardless of the result of the tests. Would it be also possible to adjust the exit code according to the rest result? 

Background is, I want to create a package for openSUSE and they advised to add automatic tests during the build process so it would be nice if a failed test would also result in an failed build.
