### ISSUE TITLE
Test suite fails to initialise using Informix

### ISSUE THREAD

**Issue by richard-reece** [mkleehammer/pyodbc#571]
Dump from the test attempt. The Informix version is `Informix Client-SDK 4.10.FC12W1`

```
$ python ../../tests2/informixtests.py 'DRIVER=<snip>'
cnxn.new cnxn=0x10d873dc8 hdbc=545883648
python:  2.7.13 (default, Aug 30 2017, 15:22:23) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
pyodbc:  4.0.22 /Users/joneri/src/pyodbc/build/lib.macosx-10.12-x86_64-2.7/pyodbc.so
odbc:    03.52
driver:  iclis09b.dylib 4.10.F                                
         supports ODBC version 03.51
os:      Darwin
unicode: Py_Unicode=2 SQLWCHAR=2
cursor.new cnxn=0x10d873dc8 hdbc=545883648 cursor=0x10dd8dc60 hstmt=545908736
Col 1: type=SQL_VARCHAR (12) colsize=128
Col 2: type=SQL_SMALLINT (5) colsize=5
Col 3: type=SQL_INTEGER (4) colsize=10
Col 4: type=SQL_VARCHAR (12) colsize=128
Col 5: type=SQL_VARCHAR (12) colsize=128
Col 6: type=SQL_VARCHAR (12) colsize=128
Col 7: type=SQL_SMALLINT (5) colsize=5
Col 8: type=SQL_SMALLINT (5) colsize=5
Col 9: type=SQL_SMALLINT (5) colsize=5
Col 10: type=SQL_SMALLINT (5) colsize=5
Col 11: type=SQL_SMALLINT (5) colsize=5
Col 12: type=SQL_SMALLINT (5) colsize=5
Col 13: type=SQL_VARCHAR (12) colsize=128
Col 14: type=SQL_SMALLINT (5) colsize=5
Col 15: type=SQL_SMALLINT (5) colsize=5
Col 16: type=SQL_SMALLINT (5) colsize=5
Col 17: type=SQL_SMALLINT (5) colsize=5
Col 18: type=SQL_INTEGER (4) colsize=10
Col 19: type=SQL_SMALLINT (5) colsize=5
ReadVarColumn: SQLGetData avail=4096 --> ret=0 cbData=28
ReadVarColumn: SQLGetData avail=4096 --> ret=0 cbData=4
ReadVarColumn: SQLGetData avail=4096 --> ret=0 cbData=4
ReadVarColumn: SQLGetData avail=4096 --> ret=0 cbData=40
ReadVarColumn: SQLGetData avail=4096 --> ret=0 cbData=28
Max VARCHAR = 255
In RaiseError(SQLGetTypeInfo)!
Traceback (most recent call last):
  File "../../tests2/informixtests.py", line 1273, in <module>
    main()
  File "../../tests2/informixtests.py", line 1257, in main
    print_library_info(cnxn)
  File "/Users/joneri/src/pyodbc/tests2/testutils.py", line 53, in print_library_info
    cursor.getTypeInfo(t)
pyodbc.Error: ('HY004', u'[HY004] [Informix][Informix ODBC Driver]SQL data type out of range. (-11064) (SQLGetTypeInfo)')
cnxn.clear cnxn=0x10d873dc8 hdbc=545883648
```

**Comment by richard-reece** [comment]
I feel I should note that once it's running the test suite fails a large majority of the tests, some 120 of the 160 tests. I've spent some time debugging them and working through some of the issues. I've managed to get one of the encoding-related tests to pass now, but I feel like the changes I've had to make to the code to make it work are probably contentious (though I honestly can't think of any way to make the tests pass without such changes.) At this point I need to re-focus back on my primary work goals, but I would like to talk about some of these issues and their potential solutions at more length if you feel that's a good idea.

**Comment by mkleehammer** [comment]
Unfortunately I don't have Informix anymore.  I wish I could get cloud versions of these from DB vendors to test against.  What is the easiest way to get a test instance that doesn't expire?

**Comment by richard-reece** [comment]
Yeah, I totally understand your pain! There is a docker image available at https://hub.docker.com/r/ibmcom/informix-developer-database/

**Comment by PyodbcUnix** [comment]
@richard-reece is it possible for you to connect to informix with pyodbc version bigger than 5.x.x and the unicode version SQLDriversConnectW() function?
