### ISSUE TITLE
Invalid Operation when trying to set transaction level

### ISSUE THREAD

**Issue by awgymer** [mkleehammer/pyodbc#811]
### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.8.2
- pyodbc: 4.0.30
- OS: MacOS 10.15.2
- DB: SQL Server
- driver: {ODBC Driver 17 for SQL Server} 

### Issue

```
>>> conn = pyodbc.connect(
...     "Driver={ODBC Driver 17 for SQL Server};"
...     "Server=myhost;Database=mydbname;"
...     "Uid=myuser;Pwd=mypwd"
... )
>>> cur = conn.cursor()
>>> cur.execute(
...     """SELECT transaction_isolation_level 
...     FROM sys.dm_exec_sessions 
...     WHERE session_id = @@SPID;""").fetchone()
(2, )
>>> cur.close()
>>> conn.set_attr(
...     pyodbc.SQL_ATTR_TXN_ISOLATION,
...     pyodbc.SQL_TXN_READ_UNCOMMITTED
... )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pyodbc.Error: ('HY011', '[HY011] [Microsoft][ODBC Driver 17 for SQL Server]Operation invalid at this time (0) (SQLSetConnectAttr)')
>>> cur = conn.cursor()
>>> cur.execute(
...     """SELECT transaction_isolation_level 
...     FROM sys.dm_exec_sessions 
...     WHERE session_id = @@SPID;""").fetchone()
(2, )
>>> cur.close()

```

This seems to regularly fail at `conn.set_attr`. I have seen it fail with or without the first select query, and it seems to fail regularly if you try to change the transaction level at all.

**Comment by v-makouz** [comment]
I can't seem to reproduce it, do you have a test app? 
Also, can you post the ODBC trace, for when the error happens?
https://www.simba.com/blog/odbc-troubleshooting-tracing/

**Comment by awgymer** [comment]
I don't have a test app, sorry. 

```
[ODBC][23385][1598518810.160079][SQLAllocHandle.c][377]
		Entry:
			Handle Type = 2
			Input Handle = 0x7faa50023400
[ODBC][23385][1598518810.160216][SQLAllocHandle.c][493]
		Exit:[SQL_SUCCESS]
			Output Handle = 0x7faa50028a00
[ODBC][23385][1598518810.160715][SQLDriverConnectW.c][290]
		Entry:
			Connection = 0x7faa50028a00
			Window Hdl = 0x0
			Str In = [Driver={ODBC Driver 17 for SQL Server};Server=myhost;Database=mydbname;Uid=myuser;Pwd=mypwd][length = 122 (SQL_NTS)]
			Str Out = 0x0
			Str Out Max = 0
			Str Out Ptr = 0x0
			Completion = 0
		UNICODE Using encoding ASCII 'UTF-8' and UNICODE 'UCS-2-INTERNAL'

[ODBC][23385][1598518810.573752][SQLDriverConnectW.c][914]
		Exit:[SQL_SUCCESS_WITH_INFO]                    
			Connection Out [[NULL]]
[ODBC][23385][1598518810.573973][SQLSetConnectAttr.c][399]
		Entry:
			Connection = 0x7faa50028a00
			Attribute = SQL_ATTR_AUTOCOMMIT
			Value = 0x0
			StrLen = -5
[ODBC][23385][1598518810.662660][SQLSetConnectAttr.c][862]
		Exit:[SQL_SUCCESS]
[ODBC][23385][1598518811.699012][SQLAllocHandle.c][540]
		Entry:
			Handle Type = 3
			Input Handle = 0x7faa50028a00
[ODBC][23385][1598518811.699141][SQLAllocHandle.c][1085]
		Exit:[SQL_SUCCESS]
			Output Handle = 0x7faa50821a00
[ODBC][23385][1598518811.701778][SQLFreeStmt.c][144]
		Entry:
			Statement = 0x7faa50821a00
			Option = 0
[ODBC][23385][1598518811.701847][SQLFreeStmt.c][266]
		Exit:[SQL_SUCCESS]
[ODBC][23385][1598518811.701981][SQLExecDirectW.c][177]
		Entry:
			Statement = 0x7faa50821a00
			SQL = [SELECT transaction_isolation_level 
    FROM sys.dm_exec_sessions 
    WHERE session_id = @@SPID;][length = 97]
[ODBC][23385][1598518811.723530][SQLExecDirectW.c][456]
		Exit:[SQL_SUCCESS]
[ODBC][23385][1598518811.723602][SQLRowCount.c][173]
		Entry:
			Statement = 0x7faa50821a00
			Row Count = 0x7ffeec2e7f50
[ODBC][23385][1598518811.723736][SQLRowCount.c][247]
		Exit:[SQL_SUCCESS]
			Row Count = 0x7ffeec2e7f50 -> -1
[ODBC][23385][1598518811.723793][SQLNumResultCols.c][156]
		Entry:
			Statement = 0x7faa50821a00
			Column Count = 0x7ffeec2e7f40
[ODBC][23385][1598518811.723842][SQLNumResultCols.c][251]
		Exit:[SQL_SUCCESS]
			Count = 0x7ffeec2e7f40 -> 1
[ODBC][23385][1598518811.723891][SQLDescribeCol.c][247]
		Entry:
			Statement = 0x7faa50821a00
			Column Number = 1
			Column Name = 0x7ffeec2e7e20
			Buffer Length = 200
			Name Length = 0x7ffeec2e7e18
			Data Type = 0x7ffeec2e7e1e
			Column Size = 0x7ffeec2e7e10
			Decimal Digits = 0x7ffeec2e7e1a
			Nullable = 0x7ffeec2e7e1c
[ODBC][23385][1598518811.723969][SQLDescribeCol.c][504]
		Exit:[SQL_SUCCESS]                
			Column Name = [transaction_isolation_level]                
			Data Type = 0x7ffeec2e7e1e -> 5                
			Column Size = 0x7ffeec2e7e10 -> 5                
			Decimal Digits = 0x7ffeec2e7e1a -> 0                
			Nullable = 0x7ffeec2e7e1c -> 0
[ODBC][23385][1598518811.724027][SQLColAttribute.c][294]
		Entry:
			Statement = 0x7faa50821a00
			Column Number = 1
			Field Identifier = SQL_DESC_UNSIGNED
			Character Attr = 0x0
			Buffer Length = 0
			String Length = 0x0
			Numeric Attribute = 0x7ffeec2e7e08
[ODBC][23385][1598518811.724081][SQLColAttribute.c][709]
		Exit:[SQL_SUCCESS]
[ODBC][23385][1598518811.724134][SQLDescribeColW.c][209]
		Entry:
			Statement = 0x7faa50821a00
			Column Number = 1
			Column Name = 0x7ffeec2e7c90
			Buffer Length = 300
			Name Length = 0x7ffeec2e7c88
			Data Type = 0x7ffeec2e7c8e
			Column Size = 0x7ffeec2e7c60
			Decimal Digits = 0x7ffeec2e7c8c
			Nullable = 0x7ffeec2e7c8a
[ODBC][23385][1598518811.724174][SQLDescribeColW.c][467]
		Exit:[SQL_SUCCESS]                
			Column Name = [transaction_isolation_level](unicode)                
			Data Type = 0x7ffeec2e7c8e -> 5                
			Column Size = 0x7ffeec2e7c60 -> 5                
			Decimal Digits = 0x7ffeec2e7c8c -> 0                
			Nullable = 0x7ffeec2e7c8a -> 0
[ODBC][23385][1598518811.724226][SQLFetch.c][162]
		Entry:
			Statement = 0x7faa50821a00
[ODBC][23385][1598518811.724274][SQLFetch.c][352]
		Exit:[SQL_SUCCESS]
[ODBC][23385][1598518811.724320][SQLGetData.c][237]
		Entry:
			Statement = 0x7faa50821a00
			Column Number = 1
			Target Type = 4 SQL_INTEGER
			Buffer Length = 4
			Target Value = 0x7ffeec2e7f08
			StrLen Or Ind = 0x7ffeec2e7f10
[ODBC][23385][1598518811.724427][SQLGetData.c][545]
		Exit:[SQL_SUCCESS]                
			Buffer = [2]                
			Strlen Or Ind = 0x7ffeec2e7f10 -> 4
[ODBC][23385][1598518811.724736][SQLFreeStmt.c][144]
		Entry:
			Statement = 0x7faa50821a00
			Option = 0
[ODBC][23385][1598518811.724781][SQLFreeStmt.c][266]
		Exit:[SQL_SUCCESS]
[ODBC][23385][1598518811.724863][SQLFreeHandle.c][387]
		Entry:
			Handle Type = 3
			Input Handle = 0x7faa50821a00
[ODBC][23385][1598518811.724905][SQLFreeHandle.c][490]
		Exit:[SQL_SUCCESS]
[ODBC][23385][1598518811.726110][SQLSetConnectAttr.c][399]
		Entry:
			Connection = 0x7faa50028a00
			Attribute = SQL_ATTR_TXN_ISOLATION
			Value = 0x2
			StrLen = -6
[ODBC][23385][1598518811.726159][SQLSetConnectAttr.c][862]
		Exit:[SQL_ERROR]
[ODBC][23385][1598518811.726258][SQLGetDiagRecW.c][535]
		Entry:
			Connection = 0x7faa50028a00
			Rec Number = 1
			SQLState = 0x7ffeec2e7f64
			Native = 0x7ffeec2e7754
			Message Text = 0x7ffeec2e7760
			Buffer Length = 1023
			Text Len Ptr = 0x7ffeec2e775e
		DIAG [HY011] [Microsoft][ODBC Driver 17 for SQL Server]Operation invalid at this time

[ODBC][23385][1598518811.726415][SQLGetDiagRecW.c][596]
		Exit:[SQL_SUCCESS]
			SQLState = [HY011]
			Native = 0x7ffeec2e7754 -> 0
			Message Text = [[Microsoft][ODBC Driver 17 for SQL Server]Operation invalid at this time]
[ODBC][23385][1598518811.726941][SQLAllocHandle.c][540]
		Entry:
			Handle Type = 3
			Input Handle = 0x7faa50028a00
[ODBC][23385][1598518811.726993][SQLAllocHandle.c][1085]
		Exit:[SQL_SUCCESS]
			Output Handle = 0x7faa4f842000
[ODBC][23385][1598518811.728610][SQLFreeStmt.c][144]
		Entry:
			Statement = 0x7faa4f842000
			Option = 0
[ODBC][23385][1598518811.728660][SQLFreeStmt.c][266]
		Exit:[SQL_SUCCESS]
[ODBC][23385][1598518811.728813][SQLExecDirectW.c][177]
		Entry:
			Statement = 0x7faa4f842000
			SQL = [SELECT transaction_isolation_level 
    FROM sys.dm_exec_sessions 
    WHERE session_id = @@SPID;][length = 97]
[ODBC][23385][1598518811.809723][SQLExecDirectW.c][456]
		Exit:[SQL_SUCCESS]
[ODBC][23385][1598518811.809949][SQLRowCount.c][173]
		Entry:
			Statement = 0x7faa4f842000
			Row Count = 0x7ffeec2e7f50
[ODBC][23385][1598518811.810693][SQLRowCount.c][247]
		Exit:[SQL_SUCCESS]
			Row Count = 0x7ffeec2e7f50 -> -1
[ODBC][23385][1598518811.810848][SQLNumResultCols.c][156]
		Entry:
			Statement = 0x7faa4f842000
			Column Count = 0x7ffeec2e7f40
[ODBC][23385][1598518811.811003][SQLNumResultCols.c][251]
		Exit:[SQL_SUCCESS]
			Count = 0x7ffeec2e7f40 -> 1
[ODBC][23385][1598518811.811122][SQLDescribeCol.c][247]
		Entry:
			Statement = 0x7faa4f842000
			Column Number = 1
			Column Name = 0x7ffeec2e7e20
			Buffer Length = 200
			Name Length = 0x7ffeec2e7e18
			Data Type = 0x7ffeec2e7e1e
			Column Size = 0x7ffeec2e7e10
			Decimal Digits = 0x7ffeec2e7e1a
			Nullable = 0x7ffeec2e7e1c
[ODBC][23385][1598518811.811266][SQLDescribeCol.c][504]
		Exit:[SQL_SUCCESS]                
			Column Name = [transaction_isolation_level]                
			Data Type = 0x7ffeec2e7e1e -> 5                
			Column Size = 0x7ffeec2e7e10 -> 5                
			Decimal Digits = 0x7ffeec2e7e1a -> 0                
			Nullable = 0x7ffeec2e7e1c -> 0
[ODBC][23385][1598518811.811385][SQLColAttribute.c][294]
		Entry:
			Statement = 0x7faa4f842000
			Column Number = 1
			Field Identifier = SQL_DESC_UNSIGNED
			Character Attr = 0x0
			Buffer Length = 0
			String Length = 0x0
			Numeric Attribute = 0x7ffeec2e7e08
[ODBC][23385][1598518811.811511][SQLColAttribute.c][709]
		Exit:[SQL_SUCCESS]
[ODBC][23385][1598518811.811662][SQLDescribeColW.c][209]
		Entry:
			Statement = 0x7faa4f842000
			Column Number = 1
			Column Name = 0x7ffeec2e7c90
			Buffer Length = 300
			Name Length = 0x7ffeec2e7c88
			Data Type = 0x7ffeec2e7c8e
			Column Size = 0x7ffeec2e7c60
			Decimal Digits = 0x7ffeec2e7c8c
			Nullable = 0x7ffeec2e7c8a
[ODBC][23385][1598518811.811750][SQLDescribeColW.c][467]
		Exit:[SQL_SUCCESS]                
			Column Name = [transaction_isolation_level](unicode)                
			Data Type = 0x7ffeec2e7c8e -> 5                
			Column Size = 0x7ffeec2e7c60 -> 5                
			Decimal Digits = 0x7ffeec2e7c8c -> 0                
			Nullable = 0x7ffeec2e7c8a -> 0
[ODBC][23385][1598518811.811914][SQLFetch.c][162]
		Entry:
			Statement = 0x7faa4f842000
[ODBC][23385][1598518811.812125][SQLFetch.c][352]
		Exit:[SQL_SUCCESS]
[ODBC][23385][1598518811.812216][SQLGetData.c][237]
		Entry:
			Statement = 0x7faa4f842000
			Column Number = 1
			Target Type = 4 SQL_INTEGER
			Buffer Length = 4
			Target Value = 0x7ffeec2e7f08
			StrLen Or Ind = 0x7ffeec2e7f10
[ODBC][23385][1598518811.812316][SQLGetData.c][545]
		Exit:[SQL_SUCCESS]                
			Buffer = [2]                
			Strlen Or Ind = 0x7ffeec2e7f10 -> 4
[ODBC][23385][1598518812.879023][SQLFreeStmt.c][144]
		Entry:
			Statement = 0x7faa4f842000
			Option = 0
[ODBC][23385][1598518812.879145][SQLFreeStmt.c][266]
		Exit:[SQL_SUCCESS]
[ODBC][23385][1598518812.879441][SQLFreeHandle.c][387]
		Entry:
			Handle Type = 3
			Input Handle = 0x7faa4f842000
[ODBC][23385][1598518812.879523][SQLFreeHandle.c][490]
		Exit:[SQL_SUCCESS]
```

That's the full ODBC trace log for the code above.

**Comment by keitherskine** [comment]
Setting the transaction level might be failing if the attempt is made in the middle of a transaction.  In your original example, I don't see a commit on the connection after the SELECT statement.  Closing the cursor doesn't commit the transaction.  Setting the transaction level probably has to be the very first statement in the database transaction, so try calling `conn.commit()` before `conn.set_attr(...)`.

**Comment by awgymer** [comment]
So it doesn't actually matter if I run that select statement or not. It will fail even if I do:

```
>>> conn = pyodbc.connect(
...     "Driver={ODBC Driver 17 for SQL Server};"
...     "Server=myhost;Database=mydbname;"
...     "Uid=myuser;Pwd=mypwd"
... )
>>> conn.set_attr(
...     pyodbc.SQL_ATTR_TXN_ISOLATION,
...     pyodbc.SQL_TXN_READ_COMMITTED
... )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pyodbc.Error: ('HY011', '[HY011] [Microsoft][ODBC Driver 17 for SQL Server]Operation invalid at this time (0) (SQLSetConnectAttr)')
>>> 
```

**Comment by keitherskine** [comment]
Hmm, that does seem odd.  If you haven't seen it before, you could try the code pattern described in the wiki here:
https://github.com/mkleehammer/pyodbc/wiki/Database-Transaction-Management#specifying-a-transaction-isolation-level
That might do the trick.

**Comment by awgymer** [comment]
Hmm, that does have `autocommit=True` to start, perhaps that is in fact required. If so it should probably just be a bit more explicit about that in the docs.
