### ISSUE TITLE
unixodbc-dev installation error

### ISSUE THREAD

**Issue by usmanfarzandali** [mkleehammer/pyodbc#818]
Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 
- pyodbc: 
- OS: Ubuntu
- DB:
- driver:

### Issue
======================================
Command

sudo pip3 install unixodbc-dev

======================================
Error

The directory '/home/usman/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/usman/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting unixodbc-dev
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 342, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python3/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 795, in get_page
    resp.raise_for_status()
  File "/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/unixodbc-dev/

Often it is easiest to describe your issue as "expected behavior" and "observed behavior".

**Comment by gordthompson** [comment]
Okay, so that should lead you to the (universally-accepted) conclusion that you **should not** be modifying the system version of Python_3. Instead, you should create a virtual environment (a.k.a. "venv") for your project and modify it for the specific requirements of that project.

**Comment by v-chojas** [comment]
unixODBC is not a Python package. The unixodbc-dev package will need to be installed using the package manager of your Linux distro, in your case `apt`. Try `apt-get install unixodbc-dev`.

**Comment by usmanfarzandali** [comment]
> apt-get install unixodbc-dev

i want install with pip please any help don't want to install apt-get ....

**Comment by gordthompson** [comment]
> 
> 
> > apt-get install unixodbc-dev
> 
> i want install with pip please any help don't want to install apt-get ....

It is simply not possible to install unixODBC with pip because unixODBC is not a Python package. You can either install it from the Ubuntu repositories (via `apt`) or you can build it from source. Those are your only options.
