### ISSUE TITLE
Error installing pyodbc on Suse Linux Enterprise 12 

### ISSUE THREAD

**Issue by dsoriafrd** [mkleehammer/pyodbc#886]
### Environment

- Python: 3.8
- OS: SLES 12 SP4 
- DB:
- driver:

### Issue
when I try to install the module with "pip install pyodbc" I get the following error:

WARNING: Discarding https://files.pythonhosted.org/packages/30/56/b7b6663664390a70f096eba8f0567d71f9a8d4b92a35d3bc5703808c8445/pyodbc-2.1.1.zip#sha256=8542a064ec8322e1ea9ba6e6bd14437bf45eb72551c8fcad0817ceda57824e2c (from https://pypi.org/simple/pyodbc/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pyodbc
ERROR: No matching distribution found for pyodbc

**Comment by gordthompson** [comment]
Version 2.1.1 is very, very old. Try `pip install pyodbc==4.0.30`

**Comment by dsoriafrd** [comment]
Thanks for replying, I get this error when installing any version

Server:~ # pip install pyodbc==4.0.30
Collecting pyodbc==4.0.30
  Downloading pyodbc-4.0.30.tar.gz (266 kB)
     |████████████████████████████████| 266 kB 16 kB/s
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jvo00quo/pyodbc_440b548ca3864546a69e2d3085f07f2b/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jvo00quo/pyodbc_440b548ca3864546a69e2d3085f07f2b/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-tjjlhtee
         cwd: /tmp/pip-install-jvo00quo/pyodbc_440b548ca3864546a69e2d3085f07f2b/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/lib/python3.8/site-packages/setuptools/__init__.py", line 18, in <module>
        from setuptools.dist import Distribution
      File "/usr/local/lib/python3.8/site-packages/setuptools/dist.py", line 34, in <module>
        from setuptools import windows_support
      File "/usr/local/lib/python3.8/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
      File "/usr/local/lib/python3.8/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ModuleNotFoundError: No module named '_ctypes'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/81/0d/bb08bb16c97765244791c73e49de9fd4c24bb3ef00313aed82e5640dee5d/pyodbc-4.0.30.tar.gz#sha256=852b5deeeb3366af8b4408efed993501708be45d221881bce60c9aac54be726a (from https://pypi.org/simple/pyodbc/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pyodbc==4.0.30
ERROR: No matching distribution found for pyodbc==4.0.30

**Comment by gordthompson** [comment]
Have you tried installing the prerequisites listed [here](https://github.com/mkleehammer/pyodbc/wiki/Install#opensuse)?

**Comment by mkleehammer** [comment]
Closing due to inactivity.  Thanks @gordthompson
