### ISSUE TITLE
using 2 params fails with db2

### ISSUE THREAD

**Issue by drewmullen** [mkleehammer/pyodbc#889]
### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 3.8.5
- pyodbc: 4.0.30
- OS: ubuntu 20
- DB: ibm db2
- driver: IBM i Access ODBC Driver

### Issue
using 2 `?` for params fails. looking for some info on what might be causing the issue. one `?` works fine fwiw

```python
>>> r = cursor.execute('''SELECT * FROM ? WHERE SSN = ?''', 'MYTABLE', '100101000')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pyodbc.ProgrammingError: ('42000', '[42000] [IBM][System i Access ODBC Driver][DB2 for i5/OS]SQL0104 - Token ? was not valid. Valid tokens: ( NEW FINAL TABLE UNNEST LATERAL XMLTABLE JSON_TABLE <IDENTIFIER>. (-104) (SQLPrepare)')

>>> r = cursor.execute('''SELECT * FROM ? WHERE SSN = ?''', ('MYTABLE', '100101000'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pyodbc.ProgrammingError: ('42000', '[42000] [IBM][System i Access ODBC Driver][DB2 for i5/OS]SQL0104 - Token ? was not valid. Valid tokens: ( NEW FINAL TABLE UNNEST LATERAL XMLTABLE JSON_TABLE <IDENTIFIER>. (-104) (SQLPrepare)'
```

thanks for this library!

**Comment by v-chojas** [comment]
I don't know about IBM i, but it's rare that an ODBC driver will support parameterising table names. The error messages suggests that it doesn't.

**Comment by drewmullen** [comment]
```python
>>> r = cursor.execute('''SELECT * FROM ? WHERE SSN = 100101000''', ('MYTABLE'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pyodbc.ProgrammingError: ('42000', '[42000] [IBM][System i Access ODBC Driver][DB2 for i5/OS]SQL0104 - Token ? was not valid. Valid tokens: ( NEW FINAL TABLE UNNEST LATERAL XMLTABLE JSON_TABLE <IDENTIFIER>. (-104) (SQLPrepare)')
```

looks like youre right! thanks @v-chojas
