### ISSUE TITLE
Memory error on "fetchall" and "fetchmany"

### ISSUE THREAD

**Issue by zlev-intel** [mkleehammer/pyodbc#896]
Hi, 
I'm using pyodbc to access postgresql database on Linux;
I'm getting the following:
>>> import pyodbc
>>> x = pyodbc.connect("Driver={PostgreSQL};SERVER=postgres5059-us-fms-in.icloud.intel.com;Port=5433;DATABASE=cloudcds_test;UID=cloudcds_test_rw;PWD=xxxxxxxxxxx;sslmode=disable")
>>> cursor = x.execute("SELECT c.column_name as COLUMN_NAME, c.data_type as DATA_TYPE, c.character_maximum_length as CHARACTER_MAXIMUM_LENGTH, c.is_nullable as IS_NULLABLE, c.column_default as COLUMN_DEFAULT   from pg_catalog.pg_statio_all_tables as st right outer join information_schema.columns c on (c.table_schema=st.schemaname and c.table_name=st.relname) where table_schema = 'da' and table_name='test_basic_table' order by ORDINAL_POSITION")
>>> cursor.fetchone()
('TestId', 'uuid', -179535464, 'NO', None)
**>>> cursor.fetchall()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
MemoryError**

The code is working OK on Windows.

Second:
>>> cursor1 = x.execute('SELECT "TestId","SubTestId","Value","RowId" FROM da.test_basic_table ORDER BY "TestId" OFFSET 0 ROWS FETCH NEXT 100 ROWS ONLY')
>>> cursor1.fetchone()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pyodbc.Error: ('07006', '[07006] Received an unsupported type from Postgres.;\nUnrecognized key passed to SQLGetInfo. (14) (SQLGetData)')

my environment:
postgresql odbc drivers: v 13.2
linux: SLES12
Python: 3.68
pyodbc: Version: 4.0.30
database: PostgreSQL 9.5 
table: 
column_name	data_type	character_maximum_length	is_nullable	column_default
TestId	uuid	(null)	NO	(null)
SubTestId	character varying	50	NO	(null)
Value	character varying	300	YES	(null)
date_time	timestamp without time zone	(null)	YES	now()
RowId	bigint	(null)	NO	nextval('da."test_basic_table_RowId_seq"'::regclass)
Value1	character varying	50	YES	(null)
Value2	character varying	50	YES	(null)

Please first make sure you have looked at:

* Documentation: https://github.com/mkleehammer/pyodbc/wiki
* Other issues

### Environment

To diagnose, we usually need to know the following, including version numbers.  On Windows, be
sure to specify 32-bit Python or 64-bit:

- Python: 

- pyodbc: 
- OS: 
- DB:
- driver:

### Issue

Often it is easiest to describe your issue as "expected behavior" and "observed behavior".

**Comment by v-chojas** [comment]
Please provide an ODBC trace.....

**Comment by zlev-intel** [comment]
> Please provide an ODBC trace.....

[odbctrace.log](https://github.com/mkleehammer/pyodbc/files/6446462/odbctrace.log)

**Comment by zlev-intel** [comment]
> Please provide an ODBC trace.....

[odbctrace.log](https://github.com/mkleehammer/pyodbc/files/6446467/odbctrace.log)

**Comment by zlev-intel** [comment]
> Please provide an ODBC trace.....

[odbctrace.log](https://github.com/mkleehammer/pyodbc/files/6446476/odbctrace.log)

**Comment by v-chojas** [comment]
```
[ODBC][17482][1620504050.431360][SQLGetData.c][237]
		Entry:
			Statement = 0xe29e30
			Column Number = 4
			Target Type = -25 SQL_C_SBIGINT
			Buffer Length = 8
			Target Value = 0x7fffffff2120
			StrLen Or Ind = 0x7fffffff2140
[ODBC][17482][1620504050.431849][SQLGetData.c][545]
		Exit:[SQL_ERROR]                
			Buffer = [Data...]                
			Strlen Or Ind = 0x7fffffff2140 -> -56880
		DIAG [07006] Received an unsupported type from Postgres.;
Unrecognized key passed to SQLGetInfo.
```
That looks like a driver issue.

**Comment by zlev-intel** [comment]
Driver is production, installed by IT from site... v13.2

And what is for first log?

**Comment by gordthompson** [comment]
> And what is for first log?

`.fetchone()` works, so can you do `.fetchmany(3)` ? If so, then you probably don't have enough memory available to do `.fetchall()`.

**Comment by zlev-intel** [comment]
There are 7 rows, small size each – query is to retrieve columns list…
Fetchmany also failed…

Thanks,
Lev Zlotin
***@***.***
+972-4-8656740
+972-53-5207679
WIKI: https://wiki.ith.intel.com/display/AETIDC (HTTP://GOTO/AETIDC )

**Comment by gordthompson** [comment]
Are you using the ANSI version of the driver (`psqlodbca.so`)? If so, try using the Unicode ("wide") version (`psqlodbcw.so`).

**Comment by gordthompson** [comment]
Closing due to inactivity. Please re-open if new information is available.
