### ISSUE TITLE
Error converting data type varchar to numeric 8114 when Inserting into SQL Server using select from values using fast_executemany

### ISSUE THREAD

**Issue by mattmorgan666** [mkleehammer/pyodbc#976]
**Environment**
Python: 3.7.3
pyodbc: 4.0.32
OS: Windows 7
DB: SQL Server 2017
driver: Microsoft ODBC Driver 17 for SQL Server msodbcsql17.dll [17.02.0000]

**Issue**

- table in a target DB with a column of type DECIMAL(18,4),
- INSERT into the Decimal column using a SELECT FROM VALUES where the select returns less columns than in the VALUES data.
- executing using executemany
- fast_executemany is turned on
- The SQL server will throw an error of 8114: Error converting data type varchar to numeric when inserting a float of value 0.09 into the column
- Trying Decimal(0.09) throws an error of Converting decimal loses precision
- Trying "0.09" works as does floats 0.01 or 0.02
- SQL is INSERT INTO {table_name} (col1, col2) (SELECT col1, col2 FROM (VALUES (?, ?, ?)) AS s (col1, col2, col3))

```
print(platform.version())
#6.1.7601

print("Python version: " + sys.version.replace("\n", ""))
#Python version: 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]

print(f"pyodbc version: {pyodbc.version}")
#pyodbc version: 4.0.32

connection_string = get_connection_string()
cnxn = pyodbc.connect(connection_string, autocommit=True)

print(
    f"ODBC driver: {cnxn.getinfo(pyodbc.SQL_DRIVER_NAME)} "
    f"[{cnxn.getinfo(pyodbc.SQL_DRIVER_VER)}]"
)
#ODBC driver: msodbcsql17.dll [17.02.0000]

crsr = cnxn.cursor()

print(crsr.execute("SELECT @@VERSION").fetchval())
#Microsoft SQL Server 2017 (RTM-GDR) (KB4505224) - 14.0.2027.2 (X64) 
#	Jun 15 2019 00:26:19 
#	Copyright (C) 2017 Microsoft Corporation
#	Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)

table_name = "mm_pyodbc"	
crsr.execute(f"DROP TABLE IF EXISTS {table_name}")
crsr.execute(f"CREATE TABLE {table_name} ([col1] [DECIMAL](18, 4) NULL, [col2] [VARCHAR](10) NULL)")	

crsr.fast_executemany = True

sql = f"INSERT INTO {table_name} (col1, col2) (SELECT col1, col2 FROM (VALUES (?, ?, ?)) AS s (col1, col2, col3))"

data = [(0.09, 'M', 'M')]
crsr.executemany(sql, data)
#Traceback (most recent call last):
#  File "<pyshell#41>", line 1, in <module>
#    crsr.executemany(sql, data)
#pyodbc.ProgrammingError: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Error converting data type varchar to numeric. (8114) (SQLExecute)')

data = [(Decimal('0.09'), 'M', 'M')]
crsr.executemany(sql, data)
Traceback (most recent call last):
  File "<pyshell#75>", line 1, in <module>
    crsr.executemany(sql, data)
pyodbc.ProgrammingError: ('Converting decimal loses precision', 'HY000')

data = [('0.09', 'M', 'M')]
crsr.executemany(sql, data) # no error here
data = [(0.01, 'M', 'M')]
crsr.executemany(sql, data) # no error here
data = [(0.02, 'M', 'M')]
crsr.executemany(sql, data) # no error here

data = [(0.03, 'M', 'M')]
crsr.executemany(sql, data)
#Traceback (most recent call last):
#  File "<pyshell#58>", line 1, in <module>
#    crsr.executemany(sql, data)
#pyodbc.ProgrammingError: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Error converting data type varchar to numeric. (8114) (SQLExecute)')

sql = f"INSERT INTO {table_name} (col1, col2) (SELECT col1, col2 FROM (VALUES (?, ?)) AS s (col1, col2))"

data = [(0.09, 'M')]
crsr.executemany(sql, data) # no error here
data = [(Decimal('0.09'), 'M')]
crsr.executemany(sql, data) # no error here

print(crsr.execute(f"SELECT * FROM {table_name}").fetchall())
#[(Decimal('0.0900'), 'M'), (Decimal('0.0100'), 'M'), (Decimal('0.0200'), 'M'), (Decimal('0.0900'), 'M'), (Decimal('0.0900'), `'M')]
```

**Comment by v-chojas** [comment]
Could you post an ODBC trace?

**Comment by mattmorgan666** [comment]
[SQL.LOG](https://github.com/mkleehammer/pyodbc/files/7469808/SQL.LOG)

**Comment by v-chojas** [comment]
> where the select returns less columns than in the VALUES data.

fast_executemany needs to determine the types of all the parameters in advance so it can allocate the parameter data array. As your trace shows, pyODBC has trouble determining those types because they're ambiguous, and the errors follow. The best solution (which also avoids sending needless data to the server) is to not do that.

**Comment by mattmorgan666** [comment]
@v-chojas - That makes sense. I had already started reworking the code to do this as a workaround anyway. Thanks for your time.
